export const DEFAULT_OPTIONS = {
  theme: 'dark', // 'dark' / 'light'
  showLabel: true,
  keyMappings: {},
};

export const KEY_LIST = [
  { key: 'Escape', label: ['esc'] },
  { key: 'F1', label: ['F1'] },
  { key: 'F2', label: ['F2'] },
  { key: 'F3', label: ['F3'] },
  { key: 'F4', label: ['F4'] },
  { key: 'F5', label: ['F5'] },
  { key: 'F6', label: ['F6'] },
  { key: 'F7', label: ['F7'] },
  { key: 'F8', label: ['F8'] },
  { key: 'F9', label: ['F9'] },
  { key: 'F10', label: ['F10'] },
  { key: 'F11', label: ['F11'] },
  { key: 'F12', label: ['F12'] },
  { key: 'Shutdown', label: ['〇'] },
  { key: '`', label: ['~', '`'] },
  { key: '1', label: ['!', '1'] },
  { key: '2', label: ['@', '2'] },
  { key: '3', label: ['#', '3'] },
  { key: '4', label: ['$', '4'] },
  { key: '5', label: ['%', '5'] },
  { key: '6', label: ['^', '6'] },
  { key: '7', label: ['&', '7'] },
  { key: '8', label: ['*', '8'] },
  { key: '9', label: ['(', '9'] },
  { key: '0', label: [')', '0'] },
  { key: '-', label: ['＿', '-'] },
  { key: '=', label: ['＋', '='] },
  { key: 'Backspace', label: ['delete'] },
  { key: 'Tab', label: ['tab'] },
  { key: 'q', label: ['Q'] },
  { key: 'w', label: ['W'] },
  { key: 'e', label: ['E'] },
  { key: 'r', label: ['R'] },
  { key: 't', label: ['T'] },
  { key: 'y', label: ['Y'] },
  { key: 'u', label: ['U'] },
  { key: 'i', label: ['I'] },
  { key: 'o', label: ['O'] },
  { key: 'p', label: ['P'] },
  { key: '[', label: ['{', '['] },
  { key: ']', label: ['}', ']'] },
  { key: '\\', label: ['|', '\\'] },
  { key: 'CapsLock', label: ['', 'CapsLock'] },
  { key: 'a', label: ['A'] },
  { key: 's', label: ['S'] },
  { key: 'd', label: ['D'] },
  { key: 'f', label: ['F'] },
  { key: 'g', label: ['G'] },
  { key: 'h', label: ['H'] },
  { key: 'j', label: ['J'] },
  { key: 'k', label: ['K'] },
  { key: 'l', label: ['L'] },
  { key: ';', label: [':', ';'] },
  { key: '\'', label: ['"', '\''] },
  { key: 'Enter', label: ['enter', 'return'] },
  { key: 'Shift', label: ['⇧'] },
  { key: 'z', label: ['Z'] },
  { key: 'x', label: ['X'] },
  { key: 'c', label: ['C'] },
  { key: 'v', label: ['V'] },
  { key: 'b', label: ['B'] },
  { key: 'n', label: ['N'] },
  { key: 'm', label: ['M'] },
  { key: ',', label: ['<', ','] },
  { key: '.', label: ['>', '.'] },
  { key: '/', label: ['?', '/'] },
  { key: 'Shift', label: ['⇧'] },
  { key: 'Fn', label: ['fn'] },
  { key: 'Control', label: ['control'] },
  { key: 'Alt', label: ['alt', 'option'] },
  { key: 'Meta', label: ['command'] },
  { key: ' ', label: [''] },
  { key: 'Meta', label: ['command'] },
  { key: 'Alt', label: ['alt', 'option'] },
  { key: 'ArrowLeft', label: ['◀'] },
  { key: 'ArrowUp', label: ['▲'] },
  { key: 'ArrowRight', label: ['▶'] },
  { key: 'ArrowDown', label: ['▼'] },
];
